name: Test

on: 
  pull_request:
    branches:
      - master

jobs:
  resty:
    name: Run test with resty
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: umegaya/lua-aws-test
    steps:
      - uses: actions/checkout@v2
      - name: Run Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }} 
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} 
          EC2_URL: ${{ secrets.EC2_URL }} 
        run: pwd && make runtest
  luajit:
    needs: resty
    name: Run test with luajit
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: umegaya/lua-aws-test-luajit
    steps:
      - uses: actions/checkout@v2
      - name: Run Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }} 
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} 
          EC2_URL: ${{ secrets.EC2_URL }} 
        run: pwd && make runtest
